import { Trade, TradePlan, User } from '../types';
import { calculateGrossPnL, calculateNetPnL, calculateRisk, calculateReward, calculateRR } from '../utils/calculations';

export const DEMO_USER: User = {
  id: 'usr_demo_trader_001',
  email: 'trader@traderos.ai',
  name: 'Dev Trader',
  createdAt: '2026-01-01T00:00:00Z',
  isOnboarded: true,
  preferences: {
    defaultCurrency: 'INR',
    startingCapital: 125000,
    defaultRiskPercent: 1.0,
    timezone: 'Asia/Kolkata',
    preferredMarkets: ['Indian Indices', 'Indian Equities', 'Crypto', 'Commodities'],
    tradingStyle: 'Intraday',
    demoMode: true,
    theme: 'dark',
    enableAIInsights: true,
  },
};

interface RawMockTrade {
  date: string;
  time: string;
  instrument: string;
  assetClass: Trade['assetClass'];
  direction: Trade['direction'];
  entry: number;
  exit: number;
  quantity: number;
  stop?: number;
  target?: number;
  strategy: string;
  timeframe: Trade['timeframe'];
  emotion: Trade['emotionalState'];
  brokerage: number;
  duration: number;
  entryReason: string;
  exitReason: string;
  notes: string;
}

const rawMockTrades: RawMockTrade[] = [
  // Day 1 - Jan 15
  {
    date: '2026-01-15',
    time: '09:35',
    instrument: 'NIFTY',
    assetClass: 'Indian Indices',
    direction: 'LONG',
    entry: 22120,
    exit: 22210,
    quantity: 50,
    stop: 22080,
    target: 22230,
    strategy: 'Breakout',
    timeframe: '5m',
    emotion: 'Disciplined',
    brokerage: 40,
    duration: 35,
    entryReason: 'Opening 15-min range breakout above VWAP with high volume',
    exitReason: 'Trailing stop hit near major psychological resistance 22200',
    notes: 'Clean execution. Followed the pre-market playbook.',
  },
  {
    date: '2026-01-15',
    time: '11:15',
    instrument: 'BANKNIFTY',
    assetClass: 'Indian Indices',
    direction: 'LONG',
    entry: 47250,
    exit: 47420,
    quantity: 30,
    stop: 47150,
    target: 47500,
    strategy: 'Pullback',
    timeframe: '15m',
    emotion: 'Confident',
    brokerage: 45,
    duration: 52,
    entryReason: 'Test of 20 EMA after morning impulse leg',
    exitReason: 'Took partials at target 1 and closed remainder on rejection',
    notes: 'Good risk control, held through initial chop.',
  },
  // Day 2 - Jan 16
  {
    date: '2026-01-16',
    time: '10:05',
    instrument: 'RELIANCE',
    assetClass: 'Indian Equities',
    direction: 'LONG',
    entry: 2880,
    exit: 2915,
    quantity: 100,
    stop: 2865,
    target: 2920,
    strategy: 'Support/Resistance',
    timeframe: '15m',
    emotion: 'Calm',
    brokerage: 50,
    duration: 80,
    entryReason: 'Daily support level double bottom confirmation',
    exitReason: 'Target reached at resistance',
    notes: 'Solid swing trade entry. Sized according to 1% account risk.',
  },
  {
    date: '2026-01-16',
    time: '14:20',
    instrument: 'NIFTY',
    assetClass: 'Indian Indices',
    direction: 'SHORT',
    entry: 22280,
    exit: 22320,
    quantity: 50,
    stop: 22310,
    target: 22200,
    strategy: 'Price Action',
    timeframe: '5m',
    emotion: 'Impulsive',
    brokerage: 40,
    duration: 18,
    entryReason: 'Thought market was overextended in afternoon',
    exitReason: 'Stop loss triggered on trend continuation',
    notes: 'Fought the trend. Need to avoid counter-trend shorts in strong uptrends.',
  },
  // Day 3 - Jan 19
  {
    date: '2026-01-19',
    time: '09:40',
    instrument: 'NIFTY',
    assetClass: 'Indian Indices',
    direction: 'LONG',
    entry: 22310,
    exit: 22405,
    quantity: 50,
    stop: 22270,
    target: 22420,
    strategy: 'Breakout',
    timeframe: '5m',
    emotion: 'Confident',
    brokerage: 40,
    duration: 42,
    entryReason: 'Gap up and go flag pattern on 5m chart',
    exitReason: 'Approaching daily R2 pivot point',
    notes: 'Strong morning momentum. Let the winner run.',
  },
  {
    date: '2026-01-19',
    time: '20:30',
    instrument: 'BTCUSDT',
    assetClass: 'Crypto',
    direction: 'LONG',
    entry: 62400,
    exit: 61850,
    quantity: 0.1,
    stop: 61900,
    target: 63800,
    strategy: 'Trend Following',
    timeframe: '1h',
    emotion: 'FOMO',
    brokerage: 30,
    duration: 110,
    entryReason: 'Saw green candle on crypto Twitter and jumped in late',
    exitReason: 'Stopped out at 4h support break',
    notes: 'Classic FOMO entry at the top of the range. Sized too heavy.',
  },
  // Day 4 - Jan 20
  {
    date: '2026-01-20',
    time: '10:10',
    instrument: 'BANKNIFTY',
    assetClass: 'Indian Indices',
    direction: 'SHORT',
    entry: 47600,
    exit: 47350,
    quantity: 30,
    stop: 47720,
    target: 47300,
    strategy: 'Support/Resistance',
    timeframe: '15m',
    emotion: 'Disciplined',
    brokerage: 45,
    duration: 75,
    entryReason: 'Bearish engulfing at swing high resistance',
    exitReason: 'Hit major target demand zone',
    notes: 'Patiently waited for the retest before entering.',
  },
  {
    date: '2026-01-20',
    time: '13:00',
    instrument: 'GOLD',
    assetClass: 'Commodities',
    direction: 'LONG',
    entry: 71200,
    exit: 71550,
    quantity: 2,
    stop: 71000,
    target: 71600,
    strategy: 'EMA',
    timeframe: '1h',
    emotion: 'Calm',
    brokerage: 60,
    duration: 140,
    entryReason: '50 EMA bounce on hourly chart with volume expansion',
    exitReason: 'Exited into resistance',
    notes: 'Commodities trade played out cleanly according to plan.',
  },
  // Day 5 - Jan 21
  {
    date: '2026-01-21',
    time: '09:20',
    instrument: 'NIFTY',
    assetClass: 'Indian Indices',
    direction: 'LONG',
    entry: 22440,
    exit: 22390,
    quantity: 75,
    stop: 22400,
    target: 22550,
    strategy: 'Breakout',
    timeframe: '5m',
    emotion: 'Greedy',
    brokerage: 45,
    duration: 15,
    entryReason: 'Increased lot size because of past winning streak',
    exitReason: 'Hit stop loss quickly on fakeout',
    notes: 'Oversized position! Kept stop tight but took unnecessary loss.',
  },
  {
    date: '2026-01-21',
    time: '09:45',
    instrument: 'NIFTY',
    assetClass: 'Indian Indices',
    direction: 'SHORT',
    entry: 22370,
    exit: 22320,
    quantity: 50,
    stop: 22410,
    target: 22280,
    strategy: 'Price Action',
    timeframe: '5m',
    emotion: 'Revenge',
    brokerage: 40,
    duration: 25,
    entryReason: 'Immediately reversed position after morning loss',
    exitReason: 'Covered early out of anxiety despite trade working',
    notes: 'Revenge trade. Even though it was positive, execution was reckless.',
  },
  // Day 6 - Jan 22
  {
    date: '2026-01-22',
    time: '10:30',
    instrument: 'TCS',
    assetClass: 'Indian Equities',
    direction: 'LONG',
    entry: 3850,
    exit: 3890,
    quantity: 50,
    stop: 3825,
    target: 3900,
    strategy: 'Pullback',
    timeframe: '15m',
    emotion: 'Calm',
    brokerage: 45,
    duration: 95,
    entryReason: 'Post-earnings consolidation breakout retest',
    exitReason: 'Near daily resistance level',
    notes: 'Textbook pullback trade. Very relaxed holding experience.',
  },
  {
    date: '2026-01-22',
    time: '19:45',
    instrument: 'BTCUSDT',
    assetClass: 'Crypto',
    direction: 'SHORT',
    entry: 63100,
    exit: 63750,
    quantity: 0.12,
    stop: 63650,
    target: 61800,
    strategy: 'Breakout',
    timeframe: '15m',
    emotion: 'Fearful',
    brokerage: 35,
    duration: 40,
    entryReason: 'Anticipating breakdown of consolidation',
    exitReason: 'Squeezed out by short covering rally',
    notes: 'Did not wait for candle close confirmation below support.',
  },
  // Day 7 - Jan 23
  {
    date: '2026-01-23',
    time: '11:00',
    instrument: 'BANKNIFTY',
    assetClass: 'Indian Indices',
    direction: 'LONG',
    entry: 47100,
    exit: 47380,
    quantity: 30,
    stop: 46980,
    target: 47400,
    strategy: 'FVG',
    timeframe: '15m',
    emotion: 'Confident',
    brokerage: 45,
    duration: 65,
    entryReason: 'Filled 15m Fair Value Gap with bullish orderflow shift',
    exitReason: 'Reached overnight high liquidity pool',
    notes: 'FVG strategy provides clear invalidation levels.',
  },
  {
    date: '2026-01-23',
    time: '14:15',
    instrument: 'NIFTY',
    assetClass: 'Indian Indices',
    direction: 'LONG',
    entry: 22350,
    exit: 22330,
    quantity: 50,
    stop: 22310,
    target: 22450,
    strategy: 'VWAP',
    timeframe: '5m',
    emotion: 'Disciplined',
    brokerage: 40,
    duration: 30,
    entryReason: 'VWAP reclaim bounce test',
    exitReason: 'Scratched trade when momentum died before close',
    notes: 'Good discipline to exit before market close with small loss.',
  },
  // Day 8 - Jan 26
  {
    date: '2026-01-26',
    time: '18:15',
    instrument: 'ETHUSDT',
    assetClass: 'Crypto',
    direction: 'LONG',
    entry: 3120,
    exit: 3240,
    quantity: 2,
    stop: 3060,
    target: 3250,
    strategy: 'Trend Following',
    timeframe: '4h',
    emotion: 'Confident',
    brokerage: 35,
    duration: 260,
    entryReason: 'Multi-day higher low formation above 200 EMA on 4h',
    exitReason: 'Reached local resistance cluster',
    notes: 'Swing trade held patiently. Allowed R:R to expand nicely.',
  },
  // Day 9 - Jan 27
  {
    date: '2026-01-27',
    time: '09:30',
    instrument: 'NIFTY',
    assetClass: 'Indian Indices',
    direction: 'LONG',
    entry: 22480,
    exit: 22590,
    quantity: 50,
    stop: 22430,
    target: 22600,
    strategy: 'Breakout',
    timeframe: '5m',
    emotion: 'Disciplined',
    brokerage: 40,
    duration: 48,
    entryReason: 'All-time high territory continuation with banking sector tailwind',
    exitReason: 'Near psychological 22600 round number',
    notes: 'Excellent risk/reward. 1:2.2 realized.',
  },
  {
    date: '2026-01-27',
    time: '13:45',
    instrument: 'HDFCBANK',
    assetClass: 'Indian Equities',
    direction: 'LONG',
    entry: 1440,
    exit: 1462,
    quantity: 100,
    stop: 1428,
    target: 1465,
    strategy: 'Support/Resistance',
    timeframe: '15m',
    emotion: 'Calm',
    brokerage: 50,
    duration: 85,
    entryReason: 'Hourly trendline support bounce with institutional block volume',
    exitReason: 'Hit intraday supply zone',
    notes: 'Very clean equity intraday move.',
  },
  // Day 10 - Jan 28
  {
    date: '2026-01-28',
    time: '10:00',
    instrument: 'BANKNIFTY',
    assetClass: 'Indian Indices',
    direction: 'SHORT',
    entry: 47550,
    exit: 47710,
    quantity: 30,
    stop: 47680,
    target: 47200,
    strategy: 'Breakout',
    timeframe: '5m',
    emotion: 'Impulsive',
    brokerage: 45,
    duration: 22,
    entryReason: 'Anticipated breakdown before candle close',
    exitReason: 'Wick swept stop loss before reversing',
    notes: 'Did not wait for 5m candle confirmation. Entry was sloppy.',
  },
  {
    date: '2026-01-28',
    time: '21:00',
    instrument: 'CRUDE OIL',
    assetClass: 'Commodities',
    direction: 'LONG',
    entry: 6250,
    exit: 6380,
    quantity: 2,
    stop: 6190,
    target: 6400,
    strategy: 'Price Action',
    timeframe: '1h',
    emotion: 'Calm',
    brokerage: 65,
    duration: 180,
    entryReason: 'Inventory data dip bought up instantly creating long lower wick',
    exitReason: 'Approaching session high resistance',
    notes: 'Well executed news digestion trade.',
  },
  // Day 11 - Jan 29
  {
    date: '2026-01-29',
    time: '09:40',
    instrument: 'NIFTY',
    assetClass: 'Indian Indices',
    direction: 'SHORT',
    entry: 22520,
    exit: 22440,
    quantity: 50,
    stop: 22560,
    target: 22420,
    strategy: 'Pullback',
    timeframe: '5m',
    emotion: 'Disciplined',
    brokerage: 40,
    duration: 38,
    entryReason: 'Failed to sustain above PDH (Previous Day High), rejected VWAP',
    exitReason: 'Covered near morning lows',
    notes: 'Clear execution of failed breakout pattern.',
  },
  {
    date: '2026-01-29',
    time: '11:30',
    instrument: 'FINNIFTY',
    assetClass: 'Indian Indices',
    direction: 'LONG',
    entry: 21100,
    exit: 21060,
    quantity: 40,
    stop: 21050,
    target: 21200,
    strategy: 'VWAP',
    timeframe: '15m',
    emotion: 'Fearful',
    brokerage: 38,
    duration: 25,
    entryReason: 'Attempted to catch falling knife at VWAP',
    exitReason: 'Cut position as selling intensified',
    notes: 'Respect the stop loss. Good cut.',
  },
  // Day 12 - Jan 30
  {
    date: '2026-01-30',
    time: '10:15',
    instrument: 'NIFTY',
    assetClass: 'Indian Indices',
    direction: 'LONG',
    entry: 22410,
    exit: 22515,
    quantity: 50,
    stop: 22360,
    target: 22520,
    strategy: 'Support/Resistance',
    timeframe: '15m',
    emotion: 'Confident',
    brokerage: 40,
    duration: 62,
    entryReason: 'Demand zone defense after morning selloff',
    exitReason: 'Hit 1:2 R:R target precisely',
    notes: 'Followed sizing and execution perfectly.',
  },
  {
    date: '2026-01-30',
    time: '14:30',
    instrument: 'BANKNIFTY',
    assetClass: 'Indian Indices',
    direction: 'LONG',
    entry: 47200,
    exit: 47120,
    quantity: 30,
    stop: 47100,
    target: 47450,
    strategy: 'Scalping',
    timeframe: '5m',
    emotion: 'Greedy',
    brokerage: 45,
    duration: 20,
    entryReason: 'Trying to squeeze out one last trade on Friday afternoon',
    exitReason: 'Stopped out during pre-expiry settlement volume',
    notes: 'Overtrading on Friday afternoon. Need a strict no-trade rule after 2 PM on Fridays.',
  },
  // Day 13 - Feb 02
  {
    date: '2026-02-02',
    time: '09:35',
    instrument: 'NIFTY',
    assetClass: 'Indian Indices',
    direction: 'LONG',
    entry: 22490,
    exit: 22610,
    quantity: 50,
    stop: 22440,
    target: 22620,
    strategy: 'Breakout',
    timeframe: '5m',
    emotion: 'Disciplined',
    brokerage: 40,
    duration: 50,
    entryReason: 'Post-budget trend continuation day 2',
    exitReason: 'Trailing stop protected majority of gains',
    notes: 'One of the best trades of the month. Kept patience.',
  },
  {
    date: '2026-02-02',
    time: '11:40',
    instrument: 'TATAMOTORS',
    assetClass: 'Indian Equities',
    direction: 'LONG',
    entry: 920,
    exit: 942,
    quantity: 150,
    stop: 908,
    target: 945,
    strategy: 'Trend Following',
    timeframe: '1h',
    emotion: 'Calm',
    brokerage: 55,
    duration: 120,
    entryReason: 'Auto sales volume surge breakout above 915 resistance',
    exitReason: 'Resistance zone profit booking',
    notes: 'Very clean price delivery.',
  },
  // Day 14 - Feb 03
  {
    date: '2026-02-03',
    time: '10:00',
    instrument: 'BTCUSDT',
    assetClass: 'Crypto',
    direction: 'LONG',
    entry: 64200,
    exit: 65150,
    quantity: 0.1,
    stop: 63600,
    target: 65200,
    strategy: 'Breakout',
    timeframe: '1h',
    emotion: 'Confident',
    brokerage: 32,
    duration: 190,
    entryReason: 'Consolidation breakout above 64,000 psychological level',
    exitReason: 'Exited at prior swing high',
    notes: 'Well managed crypto setup with conservative size.',
  },
  {
    date: '2026-02-03',
    time: '13:10',
    instrument: 'BANKNIFTY',
    assetClass: 'Indian Indices',
    direction: 'SHORT',
    entry: 47680,
    exit: 47760,
    quantity: 30,
    stop: 47750,
    target: 47400,
    strategy: 'Support/Resistance',
    timeframe: '15m',
    emotion: 'FOMO',
    brokerage: 45,
    duration: 18,
    entryReason: 'Felt it was too high without waiting for reversal candle',
    exitReason: 'Stop triggered',
    notes: 'Countertrend fighting again.',
  },
  // Day 15 - Feb 04
  {
    date: '2026-02-04',
    time: '09:45',
    instrument: 'NIFTY',
    assetClass: 'Indian Indices',
    direction: 'LONG',
    entry: 22620,
    exit: 22570,
    quantity: 50,
    stop: 22580,
    target: 22700,
    strategy: 'Pullback',
    timeframe: '5m',
    emotion: 'Calm',
    brokerage: 40,
    duration: 25,
    entryReason: 'Morning pullback to VWAP',
    exitReason: 'Stopped out as market entered narrow consolidation',
    notes: 'Acceptable loss within risk parameters.',
  },
  {
    date: '2026-02-04',
    time: '10:45',
    instrument: 'INFY',
    assetClass: 'Indian Equities',
    direction: 'LONG',
    entry: 1680,
    exit: 1712,
    quantity: 100,
    stop: 1664,
    target: 1715,
    strategy: 'EMA',
    timeframe: '15m',
    emotion: 'Disciplined',
    brokerage: 50,
    duration: 90,
    entryReason: 'Rebound from 50 EMA with strong IT sector breadth',
    exitReason: 'Approaching resistance ceiling',
    notes: 'Sector tailwind gave high probability confirmation.',
  },
  // Day 16 - Feb 05
  {
    date: '2026-02-05',
    time: '10:15',
    instrument: 'BANKNIFTY',
    assetClass: 'Indian Indices',
    direction: 'LONG',
    entry: 47400,
    exit: 47680,
    quantity: 30,
    stop: 47250,
    target: 47700,
    strategy: 'FVG',
    timeframe: '15m',
    emotion: 'Confident',
    brokerage: 45,
    duration: 70,
    entryReason: 'Clean liquidity sweep of Asia lows into 15m bullish FVG',
    exitReason: 'Target reached at fair value equilibrium',
    notes: 'Smart money concept execution was sharp.',
  },
  {
    date: '2026-02-05',
    time: '14:00',
    instrument: 'GOLD',
    assetClass: 'Commodities',
    direction: 'LONG',
    entry: 71800,
    exit: 72150,
    quantity: 2,
    stop: 71600,
    target: 72200,
    strategy: 'Trend Following',
    timeframe: '1h',
    emotion: 'Calm',
    brokerage: 60,
    duration: 150,
    entryReason: 'Higher high continuation on global safe haven demand',
    exitReason: 'Exited before US market open volatility',
    notes: 'Controlled exit ahead of US inflation numbers.',
  },
  // Day 17 - Feb 06
  {
    date: '2026-02-06',
    time: '09:30',
    instrument: 'NIFTY',
    assetClass: 'Indian Indices',
    direction: 'LONG',
    entry: 22650,
    exit: 22740,
    quantity: 50,
    stop: 22600,
    target: 22750,
    strategy: 'Breakout',
    timeframe: '5m',
    emotion: 'Disciplined',
    brokerage: 40,
    duration: 40,
    entryReason: 'Opening drive breakout above overnight resistance',
    exitReason: 'Hit primary target',
    notes: 'High conviction trade, executed without hesitation.',
  },
  {
    date: '2026-02-06',
    time: '12:15',
    instrument: 'BTCUSDT',
    assetClass: 'Crypto',
    direction: 'SHORT',
    entry: 66200,
    exit: 67100,
    quantity: 0.1,
    stop: 66900,
    target: 64800,
    strategy: 'Price Action',
    timeframe: '1h',
    emotion: 'Fearful',
    brokerage: 35,
    duration: 65,
    entryReason: 'Thought BTC was overbought near 66k',
    exitReason: 'Stop loss violated by strong breakout',
    notes: 'Underestimating crypto trend strength. Crypto shorting has poor win rate.',
  },
  // Day 18 - Feb 09
  {
    date: '2026-02-09',
    time: '09:40',
    instrument: 'NIFTY',
    assetClass: 'Indian Indices',
    direction: 'SHORT',
    entry: 22710,
    exit: 22620,
    quantity: 50,
    stop: 22750,
    target: 22600,
    strategy: 'Price Action',
    timeframe: '5m',
    emotion: 'Calm',
    brokerage: 40,
    duration: 45,
    entryReason: 'Double top rejection at 22730 with RSI bearish divergence',
    exitReason: 'Covered at 200 EMA support on 5m',
    notes: 'Divergence was clear. Good quick intraday profit.',
  },
  {
    date: '2026-02-09',
    time: '13:30',
    instrument: 'ICICIBANK',
    assetClass: 'Indian Equities',
    direction: 'LONG',
    entry: 1040,
    exit: 1061,
    quantity: 100,
    stop: 1029,
    target: 1065,
    strategy: 'Support/Resistance',
    timeframe: '15m',
    emotion: 'Confident',
    brokerage: 48,
    duration: 90,
    entryReason: 'Major horizontal support retest held with high volume',
    exitReason: 'Closed into intraday high',
    notes: 'Banking stocks remain very resilient.',
  },
  // Day 19 - Feb 10
  {
    date: '2026-02-10',
    time: '10:05',
    instrument: 'BANKNIFTY',
    assetClass: 'Indian Indices',
    direction: 'LONG',
    entry: 47800,
    exit: 48120,
    quantity: 30,
    stop: 47650,
    target: 48150,
    strategy: 'Breakout',
    timeframe: '15m',
    emotion: 'Disciplined',
    brokerage: 45,
    duration: 80,
    entryReason: 'Clean 47800 barrier breakout',
    exitReason: 'Hit 48100 target',
    notes: '+320 points captured on BankNifty. Trailed stop securely.',
  },
  {
    date: '2026-02-10',
    time: '14:40',
    instrument: 'NIFTY',
    assetClass: 'Indian Indices',
    direction: 'LONG',
    entry: 22760,
    exit: 22720,
    quantity: 50,
    stop: 22710,
    target: 22850,
    strategy: 'Scalping',
    timeframe: '5m',
    emotion: 'Greedy',
    brokerage: 40,
    duration: 20,
    entryReason: 'Tried to front-run 3 PM candle rally',
    exitReason: 'Market chopped down into settlement',
    notes: 'Another unnecessary late afternoon trade after already being up for the day.',
  },
  // Day 20 - Feb 11
  {
    date: '2026-02-11',
    time: '09:35',
    instrument: 'NIFTY',
    assetClass: 'Indian Indices',
    direction: 'LONG',
    entry: 22740,
    exit: 22825,
    quantity: 50,
    stop: 22690,
    target: 22830,
    strategy: 'Pullback',
    timeframe: '5m',
    emotion: 'Confident',
    brokerage: 40,
    duration: 35,
    entryReason: 'Morning dip to VWAP bought aggressively',
    exitReason: 'Target met near 22830',
    notes: 'Morning VWAP pullbacks on Nifty have >70% win rate for me.',
  },
  {
    date: '2026-02-11',
    time: '19:30',
    instrument: 'ETHUSDT',
    assetClass: 'Crypto',
    direction: 'LONG',
    entry: 3340,
    exit: 3260,
    quantity: 1.5,
    stop: 3270,
    target: 3480,
    strategy: 'Support/Resistance',
    timeframe: '1h',
    emotion: 'Fearful',
    brokerage: 30,
    duration: 75,
    entryReason: 'Hourly support level bounce attempt',
    exitReason: 'Support gave way under selling pressure',
    notes: 'Respect the stop loss. Clean loss.',
  },
  // Day 21 - Feb 12
  {
    date: '2026-02-12',
    time: '10:20',
    instrument: 'RELIANCE',
    assetClass: 'Indian Equities',
    direction: 'LONG',
    entry: 2940,
    exit: 2985,
    quantity: 80,
    stop: 2915,
    target: 2990,
    strategy: 'Breakout',
    timeframe: '15m',
    emotion: 'Calm',
    brokerage: 52,
    duration: 110,
    entryReason: 'Heavy call unwinding above 2950 strike',
    exitReason: 'Target 1 hit, book profit',
    notes: 'Options chain data confirmed equity strength.',
  },
  {
    date: '2026-02-12',
    time: '14:10',
    instrument: 'BANKNIFTY',
    assetClass: 'Indian Indices',
    direction: 'LONG',
    entry: 48050,
    exit: 48260,
    quantity: 30,
    stop: 47940,
    target: 48300,
    strategy: 'VWAP',
    timeframe: '5m',
    emotion: 'Disciplined',
    brokerage: 45,
    duration: 45,
    entryReason: 'VWAP pinch bounce during European market opening',
    exitReason: 'Resistance cluster at 48280',
    notes: 'Disciplined execution. No overtrading.',
  },
  // Day 22 - Feb 13
  {
    date: '2026-02-13',
    time: '09:25',
    instrument: 'NIFTY',
    assetClass: 'Indian Indices',
    direction: 'LONG',
    entry: 22840,
    exit: 22780,
    quantity: 75,
    stop: 22790,
    target: 22950,
    strategy: 'Breakout',
    timeframe: '5m',
    emotion: 'Greedy',
    brokerage: 45,
    duration: 18,
    entryReason: 'Position size doubled because feeling invincible',
    exitReason: 'Gap fill trap swept stop',
    notes: 'Oversized again! Resulted in one of the largest single trade losses.',
  },
  {
    date: '2026-02-13',
    time: '10:00',
    instrument: 'NIFTY',
    assetClass: 'Indian Indices',
    direction: 'SHORT',
    entry: 22760,
    exit: 22810,
    quantity: 75,
    stop: 22800,
    target: 22650,
    strategy: 'Price Action',
    timeframe: '5m',
    emotion: 'Revenge',
    brokerage: 45,
    duration: 14,
    entryReason: 'Anger over previous trade. Immediately shorted with heavy size',
    exitReason: 'Stopped out immediately on pullback',
    notes: 'Severe behavioral leak! Back-to-back revenge trading. Must stop trading for the day after 2 consecutive losses.',
  },
  // Day 23 - Feb 16
  {
    date: '2026-02-16',
    time: '10:30',
    instrument: 'NIFTY',
    assetClass: 'Indian Indices',
    direction: 'LONG',
    entry: 22790,
    exit: 22870,
    quantity: 50,
    stop: 22740,
    target: 22880,
    strategy: 'Pullback',
    timeframe: '15m',
    emotion: 'Calm',
    brokerage: 40,
    duration: 55,
    entryReason: 'Returned to standard lot size (50). Waited for 15m candle close.',
    exitReason: 'Target resistance at 22880',
    notes: 'Much better emotional control today after Friday disaster.',
  },
  {
    date: '2026-02-16',
    time: '20:00',
    instrument: 'BTCUSDT',
    assetClass: 'Crypto',
    direction: 'LONG',
    entry: 67100,
    exit: 68450,
    quantity: 0.1,
    stop: 66400,
    target: 68500,
    strategy: 'Breakout',
    timeframe: '4h',
    emotion: 'Disciplined',
    brokerage: 35,
    duration: 320,
    entryReason: 'Weekly consolidation breakout with sustained spot ETF inflows',
    exitReason: 'Hit major psychological target 68,500',
    notes: 'Held overnight with predefined bracket orders.',
  },
  // Day 24 - Feb 17
  {
    date: '2026-02-17',
    time: '09:40',
    instrument: 'BANKNIFTY',
    assetClass: 'Indian Indices',
    direction: 'LONG',
    entry: 48320,
    exit: 48590,
    quantity: 30,
    stop: 48180,
    target: 48600,
    strategy: 'Breakout',
    timeframe: '5m',
    emotion: 'Confident',
    brokerage: 45,
    duration: 60,
    entryReason: 'Morning all-time high breakout with PSU Banks leading',
    exitReason: 'Partial profit booking near 48600',
    notes: '+270 points in BankNifty. Flawless execution.',
  },
  {
    date: '2026-02-17',
    time: '13:00',
    instrument: 'GOLD',
    assetClass: 'Commodities',
    direction: 'LONG',
    entry: 72300,
    exit: 72720,
    quantity: 2,
    stop: 72050,
    target: 72800,
    strategy: 'Trend Following',
    timeframe: '1h',
    emotion: 'Calm',
    brokerage: 60,
    duration: 130,
    entryReason: 'Hourly trendline bounce with dollar index weakening',
    exitReason: 'Resistance rejection',
    notes: 'Gold continues to be a very reliable trend asset.',
  },
  // Day 25 - Today / Recent
  {
    date: '2026-02-18',
    time: '09:30',
    instrument: 'NIFTY',
    assetClass: 'Indian Indices',
    direction: 'LONG',
    entry: 22880,
    exit: 22965,
    quantity: 50,
    stop: 22830,
    target: 22970,
    strategy: 'Breakout',
    timeframe: '5m',
    emotion: 'Disciplined',
    brokerage: 40,
    duration: 35,
    entryReason: 'Opening drive gap-and-go pattern',
    exitReason: 'Target met at 22965',
    notes: 'First trade today. Hit target clean in 35 minutes.',
  },
  {
    date: '2026-02-18',
    time: '11:15',
    instrument: 'BANKNIFTY',
    assetClass: 'Indian Indices',
    direction: 'LONG',
    entry: 48550,
    exit: 48690,
    quantity: 30,
    stop: 48420,
    target: 48750,
    strategy: 'Pullback',
    timeframe: '15m',
    emotion: 'Confident',
    brokerage: 45,
    duration: 48,
    entryReason: '15m pullback to VWAP and previous resistance turned support',
    exitReason: 'Took profit on momentum pause',
    notes: 'Second trade today. Disciplined win.',
  },
  {
    date: '2026-02-18',
    time: '14:10',
    instrument: 'RELIANCE',
    assetClass: 'Indian Equities',
    direction: 'SHORT',
    entry: 2990,
    exit: 3005,
    quantity: 80,
    stop: 3004,
    target: 2950,
    strategy: 'Price Action',
    timeframe: '15m',
    emotion: 'Fearful',
    brokerage: 50,
    duration: 25,
    entryReason: 'Tried to short resistance level before 3 PM',
    exitReason: 'Stop hit on final hour index rally',
    notes: 'Third trade today. Loss kept small to preserve daily profit.',
  },
];

/**
 * Builds fully computed trades matching all data model requirements.
 */
export function generateDemoTrades(userId: string = DEMO_USER.id): Trade[] {
  return rawMockTrades.map((raw, index) => {
    const gross = calculateGrossPnL(raw.direction, raw.entry, raw.exit, raw.quantity);
    const charges = {
      brokerage: raw.brokerage,
      stt: Number((raw.entry * raw.quantity * 0.000125).toFixed(2)),
      exchangeCharges: Number((raw.entry * raw.quantity * 0.000035).toFixed(2)),
      gst: Number((raw.brokerage * 0.18).toFixed(2)),
      sebiCharges: Number((raw.entry * raw.quantity * 0.000001).toFixed(2)),
      otherCharges: 0,
      totalCharges: 0,
    };
    charges.totalCharges = Number(
      (
        charges.brokerage +
        charges.stt +
        charges.exchangeCharges +
        charges.gst +
        charges.sebiCharges
      ).toFixed(2)
    );

    const net = calculateNetPnL(gross, charges);
    const capitalUsed = Number((raw.entry * raw.quantity * (raw.assetClass.includes('Indices') ? 0.2 : 1)).toFixed(2));
    const pnlPercentage = capitalUsed > 0 ? Number(((net / capitalUsed) * 100).toFixed(2)) : 0;
    const risk = calculateRisk(raw.direction, raw.entry, raw.stop, raw.quantity);
    const reward = calculateReward(raw.direction, raw.entry, raw.target, raw.quantity);
    const rr = calculateRR(risk, reward);

    return {
      id: `demo_trade_${String(index + 1).padStart(3, '0')}`,
      userId,
      date: raw.date,
      time: raw.time,
      instrument: raw.instrument,
      assetClass: raw.assetClass,
      direction: raw.direction,
      entryPrice: raw.entry,
      exitPrice: raw.exit,
      quantity: raw.quantity,
      capitalUsed,
      stopLoss: raw.stop,
      target: raw.target,
      strategy: raw.strategy,
      timeframe: raw.timeframe,
      entryReason: raw.entryReason,
      exitReason: raw.exitReason,
      notes: raw.notes,
      emotionalState: raw.emotion,
      charges,
      grossPnL: gross,
      netPnL: net,
      pnlPercentage,
      riskAmount: risk,
      rewardAmount: reward,
      rrRatio: rr,
      holdingDurationMinutes: raw.duration,
      isWin: net > 0,
      isBreakEven: net === 0,
      createdAt: `${raw.date}T${raw.time}:00Z`,
      updatedAt: `${raw.date}T${raw.time}:00Z`,
    };
  });
}

export const DEMO_TRADE_PLANS: TradePlan[] = [
  {
    id: 'plan_001',
    userId: DEMO_USER.id,
    instrument: 'NIFTY',
    assetClass: 'Indian Indices',
    direction: 'LONG',
    entryZoneMin: 22880,
    entryZoneMax: 22910,
    stopLoss: 22830,
    target: 23050,
    rrRatio: 2.6,
    suggestedPositionSize: 50,
    timeframe: '15m',
    reason: 'Pullback toward 15m VWAP & 50 EMA cluster with strong market breadth',
    status: 'PLANNED',
    date: '2026-02-18',
    createdAt: '2026-02-18T08:30:00Z',
    updatedAt: '2026-02-18T08:30:00Z',
  },
  {
    id: 'plan_002',
    userId: DEMO_USER.id,
    instrument: 'BTCUSDT',
    assetClass: 'Crypto',
    direction: 'LONG',
    entryZoneMin: 67200,
    entryZoneMax: 67500,
    stopLoss: 66400,
    target: 70000,
    rrRatio: 2.8,
    suggestedPositionSize: 0.1,
    timeframe: '4h',
    reason: 'Breakout retest of prior weekly swing high',
    status: 'EXECUTED',
    date: '2026-02-16',
    createdAt: '2026-02-16T18:00:00Z',
    updatedAt: '2026-02-16T20:00:00Z',
  },
  {
    id: 'plan_003',
    userId: DEMO_USER.id,
    instrument: 'GOLD',
    assetClass: 'Commodities',
    direction: 'LONG',
    entryZoneMin: 72100,
    entryZoneMax: 72350,
    stopLoss: 71900,
    target: 73000,
    rrRatio: 2.4,
    suggestedPositionSize: 2,
    timeframe: '1h',
    reason: 'Hourly trendline bounce with macro tailwind',
    status: 'PLANNED',
    date: '2026-02-18',
    createdAt: '2026-02-18T12:00:00Z',
    updatedAt: '2026-02-18T12:00:00Z',
  },
];
